### ISSUE TITLE
Version 1.9 for ILIAS 6 - No plugin configuration

### ISSUE THREAD

**Issue by zone11** [ilifau/assAccountingQuestion#3]
After the upgrade to ILIAS 6.4 and Plugin 1.9 the configuration button in the plugin administration -> actions has gone. Reinstallation of the plugin doesn't help.

**Comment by fneumann** [comment]
I now merged the configuration of the thousands delimiters to the master-ilias6 branch. Could you check if they work fine?

**Comment by zone11** [comment]
It looks good on the local test installation. I'll give it a go in production with the next service window.

**Comment by zone11** [comment]
Sorry for the very late feedback. The configuration tab is now available.
