### ISSUE TITLE
ILIAS 8 Support

### ISSUE THREAD

**Issue by zone11** [ilifau/assAccountingQuestion#6]
Are there any plans to support ILIAS 8 in the near future?

End of maintenance for version 7 is expected in April 2024.

**Comment by fneumann** [comment]
I plan to create beta version of the plugin for ILIAS 8 by the end of next week (Nov. 19). As the plugin allows rather complex settings, I would appreciate any help for beta testing it with real questions.

**Comment by zone11** [comment]
Sounds great, I would love to support with one of our teachers who uses your plugin on a regular base here.
We're going to setup a test system wich should be available at the end of the month.
